<?php

namespace app\models;

class BusinessType
{
    const GROUP = 'GROUP';
    const PETERNAKAN = 'PETERNAKAN';
    const JASA_TRANSPORTASI_ANGKUT_DARAT = 'JASA TRANSPORTASI ANGKUT DARAT';
    const JASA_TRANSPORTASI_ANGKUT_LAUT_UDARA = 'JASA TRANSPORTASI ANGKUT LAUT & UDARA';
    const TELEKOMUNIKASI = 'TELEKOMUNIKASI';
    const TEMPAT_WISATA = 'TEMPAT WISATA';
    const INDUSTRI_PEMBUATAN_PERAKITAN = 'INDUSTRI PEMBUATAN & PERAKITAN';
    const INDUSTRI_PERTAMBANGAN = 'INDUSTRI PERTAMBANGAN';
    const PASAR_TRADISIONAL_PKL = 'PASAR TRADISIONAL & PKL';
    const JASA_KEUANGAN = 'JASA KEUANGAN';
    const JASA_KONSULTAN_TEKNIS = 'JASA KONSULTAN & TEKNIS';
    const JASA_SURVEY = 'JASA SURVEY';
    const JASA_PENJUALAN = 'JASA PENJUALAN';
    const JASA_KESEHATAN = 'JASA KESEHATAN';
    const PARTAI_POLITIK = 'PARTAI POLITIK';
    const DPR_DPRD = 'DPR / DPRD';
    const PENDIDIKAN_FORMAL = 'PENDIDIKAN FORMAL';
    const PENDIDIKAN_INFORMAL = 'PENDIDIKAN INFORMAL';
    const MULTIMEDIA_ENTERTAINMENT = 'MULTIMEDIA & ENTERTAINMENT';
    const KOMUNITAS = 'KOMUNITAS';

    public static function businessTypes()
    {
        return [
            self::GROUP => self::GROUP,
            self::PETERNAKAN => self::PETERNAKAN,
            self::JASA_TRANSPORTASI_ANGKUT_DARAT => self::JASA_TRANSPORTASI_ANGKUT_DARAT,
            self::JASA_TRANSPORTASI_ANGKUT_LAUT_UDARA => self::JASA_TRANSPORTASI_ANGKUT_LAUT_UDARA,
            self::TELEKOMUNIKASI => self::TELEKOMUNIKASI,
            self::TEMPAT_WISATA => self::TEMPAT_WISATA,
            self::INDUSTRI_PEMBUATAN_PERAKITAN => self::INDUSTRI_PEMBUATAN_PERAKITAN,
            self::INDUSTRI_PERTAMBANGAN => self::INDUSTRI_PERTAMBANGAN,
            self::PASAR_TRADISIONAL_PKL => self::PASAR_TRADISIONAL_PKL,
            self::JASA_KEUANGAN => self::JASA_KEUANGAN,
            self::JASA_KONSULTAN_TEKNIS => self::JASA_KONSULTAN_TEKNIS,
            self::JASA_SURVEY => self::JASA_SURVEY,
            self::JASA_PENJUALAN => self::JASA_PENJUALAN,
            self::JASA_KESEHATAN => self::JASA_KESEHATAN,
            self::PARTAI_POLITIK => self::PARTAI_POLITIK,
            self::DPR_DPRD => self::DPR_DPRD,
            self::PENDIDIKAN_FORMAL => self::PENDIDIKAN_FORMAL,
            self::PENDIDIKAN_INFORMAL => self::PENDIDIKAN_INFORMAL,
            self::MULTIMEDIA_ENTERTAINMENT => self::MULTIMEDIA_ENTERTAINMENT,
            self::KOMUNITAS => self::KOMUNITAS,
        ];
    }
}
