<?php
require('fpdf.php');

$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','B',16);
// $pdf->Cell(40,10,'Hello World!');
$pdf->Image('img-reliance-life.jpg', 10, 10, -200);
$pdf->SetY(30);
$pdf->SetX(0);
$pdf->SetFont('Arial','B',8);
$pdf->Cell($pdf->GetPageWidth(), 5, 'SERTIFIKAT ASURANSI', 0, 1, 'C');
$pdf->SetY($pdf->GetY() + 2);
$pdf->SetX(0);
$pdf->SetFont('Arial','B',11);
$pdf->Cell($pdf->GetPageWidth(), 5, 'NOMOR : '. '<<Nomor Sertifikat>>', 0, 1, 'C');
$pdf->SetY($pdf->GetY() + 10);
$pdf->SetX(10);
$pdf->SetFont('Arial','',8);
$pdf->Cell(40, 5, 'Nomor Polis', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Nomor Polis>>', 0, 1, 'L');
$pdf->Cell(40, 5, 'Nama', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Nama>>', 0, 1, 'L');
$pdf->Cell(40, 5, 'Nomor Peserta', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Nomor Peserta>>', 0, 1, 'L');
$pdf->Cell(40, 5, 'Tanggal Lahir', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Tanggal Lahir>>', 0, 1, 'L');
$pdf->SetY($pdf->GetY() + 10);
$pdf->SetX(10);
$pdf->Cell($pdf->GetPageWidth(), 5, 'Adalah Peserta Polis Dari Asuransi Jiwa (Pemegang Polis)', 0, 0, 'L');
$pdf->SetY($pdf->GetY() + 25);
$pdf->SetX(0);
$pdf->SetFont('Arial','B',8);
$pdf->Cell($pdf->GetPageWidth(), 5, 'BANK JAWA TIMUR', 0, 1, 'C');
$pdf->SetFont('Arial','',8);
$pdf->SetY($pdf->GetY() + 10);
$pdf->SetX(10);
$pdf->Cell($pdf->GetPageWidth(), 5, 'Dengan ketentuan sebagai berikut :', 0, 0, 'L');
$pdf->SetY($pdf->GetY() + 10);
$pdf->SetX(10);
$pdf->Cell(40, 5, 'Jenis Asuransi', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Jenis Asuransi>>', 0, 1, 'L');
$pdf->Cell(40, 5, 'Masa Asuransi', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Masa Asuransi>>', 0, 1, 'L');
$pdf->Cell(40, 5, 'Periode Asuransi', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Periode Asuransi>>', 0, 1, 'L');
$pdf->Cell(40, 5, 'Uang Pertanggungan', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Uang Pertanggungan>>', 0, 1, 'L');
$pdf->Cell(40, 5, 'Premi Gross', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Premi Gross>>', 0, 1, 'L');
$pdf->Cell(40, 5, 'Extra Premi', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Extra Premi>>', 0, 1, 'L');
$pdf->Cell(40, 5, 'Total Premi', 0, 0, 'L');
$pdf->Cell(5, 5, ':', 0, 0, 'L');
$pdf->Cell($pdf->GetPageWidth() - 65, 5, '<<Total Premi>>', 0, 1, 'L');
$pdf->SetY($pdf->GetY() + 10);
$pdf->Cell($pdf->GetPageWidth() - 20, 5, 'Jakarta, <<Tanggal Print>>', 0, 1, 'R');
$pdf->Image('policy-qr.png', $pdf->GetPageWidth() - 40, $pdf->GetY() + 2, -100);
$pdf->SetY($pdf->GetY() + 22);
$pdf->SetFont('Arial','B',8);
$pdf->Cell($pdf->GetPageWidth() - 31, 5, 'Aisyah Aini', 0, 1, 'R');
$pdf->SetFont('Arial','',8);
$pdf->Cell($pdf->GetPageWidth() - 31, 5, 'Underwriting', 0, 1, 'R');

$pdf->Output('', '');
//F => parameter save file , paramater kedua => path tempat pdf di create
// $pdf->Output('F', '../..');
?>